### ISSUE TITLE
Remove "Core device properties" from "Sysman Device Properties" structure

### ISSUE THREAD

**Issue by saik-intel** [oneapi-src/level-zero#112]
with zesInit() introduced, sysman is independent of core for getting devic

[ze_device_properties_t](https://spec.oneapi.io/level-zero/latest/core/api.html#_CPPv422ze_device_properties_t) core
[out] **Core device properties** 

https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv423zes_device_properties_t

can we get rid of core device properties from sysman ? Unless any sysman user interested to get core device properties from sysman ?

**Comment by bmyates** [comment]
It would need to be retained for backwards compatibility until 2.0, but it could be marked as deprecated if there is no reason to prefer it over the core device properties.

**Comment by jandres742** [comment]
@saik-intel this question belongs to the level-zero-spec repo.

**Comment by saik-intel** [comment]
created https://github.com/intel-innersource/libraries.compute.oneapi.level-zero.spec/issues/105
