### ISSUE TITLE
Remove COVFILE from release for v1.10.0

### ISSUE THREAD

**Issue by ZzEeKkAa** [oneapi-src/level-zero#114]
Whenever I run `sycl-ls` I get 
`BullseyeCoverage 8.25.25 error 15: Cannot find /home/<username>/test.cov, errno=2 "No such file or directory". COVFILE is not set. Program=sycl-ls`

Downgrading to `1.9.9` resolves the problem

**Comment by bmyates** [comment]
I changed the packages, please try what is posted now and confirm if it fixes the problem

**Comment by ZzEeKkAa** [comment]
Yes, it is ubuntu22 behind WSL2.
New package resolved the issue, thank you!
