### ISSUE TITLE
libze_loader.so.1: cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by zkvii** [oneapi-src/level-zero#125]
when following official intel_extension_for_pytorch xpu install tutorial, I came out with
```
libze_loader.so.1: cannot open shared object file: no such file or directory
```
my env is as follows
- wsl2-ubuntu22.04
- arc driver 4952
- python 3.8.11
- torch==2.0.1a0 torchvision==0.15.2a0 intel_extension_for_pytorch==2.0.110+xpu
- oneapi-basekit 2023.2.0
---
finally I found install old version leverl-zero **v1.13.5** could solve the problem.
Posted for those who find it useful.

**Comment by eero-t** [comment]
Which version of level-zero package has this issue, and where it was installed from (see #128)?

**Comment by zkvii** [comment]
> Which version of level-zero package has this issue, and where it was installed from (see #128)?

Using **v1.13.5** can solve this error, but the updated versions probably won't work. I
In fact, I didn't know which version caused this issue. I simply installed the 2023 version of **one-basekit**, and when using XPU for hardware acceleration, this error occurred. It suggested it might be related to the **Level-Zero** package. So, I installed the latest Level-Zero, which is currently **v1.15.1**. However, the error persisted. Then, I tried installing an older version and found that installing v1.13.5 resolved the issue. I hope my answer helps you.

**Comment by eero-t** [comment]
> So, I installed the latest Level-Zero, which is currently **v1.15.1**. However, the error persisted.

**Where** you installed it from?

**Comment by eero-t** [comment]
@zkvii In case you were installing *.deb packages from the release notes: https://github.com/oneapi-src/level-zero/releases/tag/v1.15.1

File paths in those are now fixed (see #128).

**Comment by zkvii** [comment]
> > So, I installed the latest Level-Zero, which is currently **v1.15.1**. However, the error persisted.
> 
> Where you installed it **from**?

yep, the deb file's install path is strange as #128

**Comment by eero-t** [comment]
@zkvii as the packages were fixed (already last year), could you close this (I cannot)?

**Comment by 5001945** [comment]
For those of you still struggling with this error in 2024 (like me), try typing `conda install level-zero -c conda-forge`.
