### ISSUE TITLE
Preferred abbreviation: ZE or L0?

### ISSUE THREAD

**Issue by al42and** [oneapi-src/level-zero#126]
All [spec-mandated symbols](https://spec.oneapi.io/level-zero/latest/core/INTRO.html#naming-convention) and filenames use `ze` prefix. But outside the LevelZero spec, "L0" is widely used to refer to it, and sometimes it's a mix of both:

https://github.com/oneapi-src/level-zero/blob/ea5be99d8d34480447ab1e3c7efc30d6f179b123/source/lib/ze_lib.cpp#L46

Are there any guidelines on which shorthand to use when?

**Comment by bmyates** [comment]
One of the reasons ze was chosen as the namespace prefix rather than "l0" is because both both characters "l" and "0" are ambiguous depending on font choice.      You are free to use whatever shorthand you like of course.
