### ISSUE TITLE
Intel level zero Compute is broken for my Intel Arc A750LE with linux kernel version 6.6.27 and above

### ISSUE THREAD

**Issue by qnixsynapse** [oneapi-src/level-zero#147]
The compute hangs with no error on the front facing application using level-zero. In the system logs however, I can see this error:

```
kernel: Fence expiration time out i915-0000:03:00.0:server[5816]:14c!
```

I suspect that the problem might related to [this upstream commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-rolling-lts&id=0a9901fdb7bb785ec4975aeeebc1428e3abae172) .

I can also see that the number of physical "unknown" engines in intel_gpu_top has been reduced to 1 from 4. Not sure where to open the issue, so I am opening here first.

**Comment by portaloffreedom** [comment]
I'm experiencing a very similar issue with blender. The entire KDE locks and `dmesg` reports
```
Fence expiration time out i915-0000:44:00.0:blender[11880]:2!
```

if I use `SYCL_PI_TRACE=-1 blender --debug-cycles` only blender hangs instead of the entire UI, last command reported by PI_TRACE is 
```
---> piQueueFinish(
        <unknown> : 0x72611e81de00
```

**Comment by qnixsynapse** [comment]
Mine hangs right here:
```
UR ---> Queue->executeCommandList(CommandList, false, OkToBatch)
UR <--- Queue->executeCommandList(CommandList, false, OkToBatch)(UR_RESULT_SUCCESS)
) ---> 	pi_result : PI_SUCCESS
	[out]void * : 0xffffd5579d000000
	[out]pi_event * : 0[ nullptr ]
	[out]pi_event * : 0x454a208[ 0x4548590 ... ]

---> piEventRelease(
	pi_event : 0x4548a00
UR ---> urEventReleaseInternal(Event)
UR ---> urQueueReleaseInternal(Queue)
UR <--- urQueueReleaseInternal(Queue)(UR_RESULT_SUCCESS)
UR <--- urEventReleaseInternal(Event)(UR_RESULT_SUCCESS)
) ---> 	pi_result : PI_SUCCESS

---> piEventsWait(
	<unknown> : 1
	pi_event * : 0x454a208[ 0x4548590 ... ]
UR ---> UrQueue->executeAllOpenCommandLists()
UR <--- UrQueue->executeAllOpenCommandLists()(UR_RESULT_SUCCESS)
```

Not sure what that means since I am not an expert in low level GPU programming.

**Comment by portaloffreedom** [comment]
I found the corresponding issue on blender side: https://projects.blender.org/blender/blender/issues/120800

**Comment by portaloffreedom** [comment]
And found this as well: https://github.com/intel/compute-runtime/issues/726

**Comment by qnixsynapse** [comment]
Okay, it is [a kernel module bug introduced in 6.6.26 and above](https://gitlab.freedesktop.org/drm/i915/kernel/-/issues/10955#note_2402312).
