### ISSUE TITLE
Add a way to translate from/to ZES/ZE device handle when using zesInit()

### ISSUE THREAD

**Issue by bgoglin** [oneapi-src/level-zero#153]
Followup to https://github.com/intel/compute-runtime/issues/686#issuecomment-1805025932 

We need a way to translate from/to ZE/ZES device handles when using zesInit(). This is needed to be able to query some device info from ZES and combine it with ZE info. It was reported under work but I still cannot find it and couldn't get a reply on the specification/implementation status.

**Comment by saik-intel** [comment]
hi @bgoglin  we have added APIs to map based on UUID of device in spec 1.9 https://spec.oneapi.io/level-zero/latest/sysman/api.html#sysmandevicemapping and implementation is under work in progress and will expect to avaliable by June 2024 end

**Comment by bgoglin** [comment]
> hi @bgoglin we have added APIs to map based on UUID of device in spec 1.9 https://spec.oneapi.io/level-zero/latest/sysman/api.html#sysmandevicemapping and implementation is under work in progress and will expect to avaliable by June 2024 end

Hello. Can you update me regarding the implementation status? If done, which releases started having it?

**Comment by saik-intel** [comment]
We are planning to document the same on spec @bgoglin   , please see https://github.com/intel-innersource/libraries.compute.oneapi.level-zero.spec/issues/151

**Comment by saik-intel** [comment]
@bgoglin   also please go through https://oneapi-src.github.io/level-zero-spec/level-zero/latest/sysman/api.html#sysmandevicemapping-functions   APIs for mapping from core device handle -> sysman device handle

**Comment by AshwinKumarKulkarni** [comment]
please find below some steps about mapping core device handle to sysman device handle and vice versa when using zesInit().

Mapping core handle to sysman handle:
-------------------------------------
1. Get UUID of core handle from "zeDeviceGetProperties(ze_device_handle_t hDevice, ze_device_properties_t *pDeviceProperties)". 
(note down ze_device_properties_t.uuid)

2.please pass UUID along with sysman driver handle to "zesDriverGetDeviceByUuidExp(zes_driver_handle_t hDriver, zes_uuid_t uuid, zes_device_handle_t *phDevice, ze_bool_t *onSubdevice, uint32_t *subdeviceId)" to get sysman handle as "phDevice" equivalent to core handle.
Note: hDriver should be got from zesDriverGet().

Mapping sysman handle to core handle:
--------------------------------------
1. Get UUID of the sysman device handle from "zesDeviceGetProperties(zes_device_handle_t hDevice, zes_device_properties_t *pProperties)" for sysman device
and if zes_device_properties_t.numSubdevices > 0, then get UUIDs of sub devices using "zesDeviceGetSubDevicePropertiesExp(zes_device_handle_t hDevice, uint32_t *pCount, zes_subdevice_exp_properties_t *pSubdeviceProps)".

2. Using the UUID of sysman device handle of interest, it is possible to compare UUIDs of the core device handles got from "zeDeviceGetProperties(ze_device_handle_t hDevice, ze_device_properties_t *pDeviceProperties)" to get the mapping core device handle.

**Comment by bgoglin** [comment]
I am closing this since things work in hwloc now. However, I'd still like an answer to the question above about which version first supported zesDriverGetDeviceByUuidExp(). Overall, I really dislike the idea of adding a no-op function to respect the spec and later actually implement it. This has been a nightmare for us several times in the past.

**Comment by AshwinKumarKulkarni** [comment]
Hi @bgoglin , you can find the  zesDriverGetDeviceByUuidExp() API supported from libze_intel_gpu.so.1.x.**xxxxx** where xxxxx is greater than 30220.

**Comment by bgoglin** [comment]
> Hi @bgoglin , you can find the zesDriverGetDeviceByUuidExp() API supported from libze_intel_gpu.so.1.x.**xxxxx** where xxxxx is greater than 30220.

Any idea where to find RHEL (9.4) packages with this? The doc [1] currently points to some "lts/2350" RPM repository which contains a much older libze_intel_gpu.so.1.3.27642.66

[1] https://dgpu-docs.intel.com/driver/installation.html
