### ISSUE TITLE
timeouts should be 64-bit as 4 seconds might not be enough

### ISSUE THREAD

**Issue by airlied** [oneapi-src/level-zero#17]
UINT32_MAX in nanoseconds is just over 4 seconds which seems to short. All timeouts should be uint64_t for future proofiing.

**Comment by gatorfax** [comment]
We agree this is an issue that needs to be fixed.  We are still discussing the pros and cons of few different options.  But we should have this addressed in our next spec update.

**Comment by gatorfax** [comment]
See an example in the latest spec:
[zeEventHostSynchronize](https://spec.oneapi.com/level-zero/latest/core/api.html#zeeventhostsynchronize)

**Comment by kevin-harms** [comment]
The 1.1.2 specification provides a 64 bit timeout. 
https://spec.oneapi.com/level-zero/latest/sysman/api.html#zesdrivereventlistenex

Can we close this issue?

**Comment by kevin-harms** [comment]
The 1.1.2 specification provides a 64 bit timeout. 
https://spec.oneapi.com/level-zero/latest/sysman/api.html#zesdrivereventlistenex

Can we close this issue?
