### ISSUE TITLE
exposing maxMemAllocSize via ze_device_memory_properties_t

### ISSUE THREAD

**Issue by 8tab** [oneapi-src/level-zero#18]
Is it possible to expose maxMemAllocSize via ze_device_memory_properties_t?
Currently, level_zero implementation for Intel GPU uses this property to check if size is valid or not (e.g. https://github.com/intel/compute-runtime/blob/master/level_zero/core/source/memory/memory.cpp#L123) and it seems that the user doesn't have a way to know what its value is (besides looking at compute-runtime source code).

**Comment by gatorfax** [comment]
Apologies for the delay in responding to this.  I needed to get confirmation from our driver team on some of the details.  I've updated the spec to include this in `ze_device_properties_t`.  You should see this in the next version.  Thank you for your contribution.

**Comment by 8tab** [comment]
Is it already published? If yes, where should I look for it? I couldn't find it here https://spec.oneapi.com/level-zero/latest/core/api.html?highlight=ze_device_properties_t#_CPPv422ze_device_properties_t nor here https://spec.oneapi.com/level-zero/latest/core/api.html?highlight=ze_device_memory_properties_t#_CPPv429ze_device_memory_properties_t.

**Comment by gatorfax** [comment]
it has not been published yet. we are working on getting the latest spec published asap.

**Comment by kevin-harms** [comment]
The current 1.1.2 spec has a uint64_t maxMemAllocSize field in the ze_device_properties_t.
https://spec.oneapi.com/level-zero/latest/core/api.html#_CPPv4N22ze_device_properties_t15maxMemAllocSizeE

Can we close this issue?

**Comment by 8tab** [comment]
Yes, thank you
