### ISSUE TITLE
Driver not initialized: ZE_RESULT_ERROR_UNINITIALIZED

### ISSUE THREAD

**Issue by Meldryt** [oneapi-src/level-zero#196]
I'm trying to run the zello_world example on Windows 10 and it fails:

```
zello_world.exe
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path:
ZE_LOADER_DEBUG_TRACE:Loading Driver C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_eb1c0bb4c867d89a\ze_intel_gpu64.dll
ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll
Driver not initialized: ZE_RESULT_ERROR_UNINITIALIZED
Did NOT find matching ZE_DEVICE_TYPE_GPU device!
```

I have Intel HD Graphics 630 (Kaby-Lake-H-GT2, Gen. 9.5) with the newest intel drivers.
(31.0.101.2130). Its supported according to the list (https://github.com/intel/compute-runtime?tab=readme-ov-file#supported-platforms)

What is exactly missing or in wrong location?

edit:

Debugged and found out that during initialization 
zeDdiTableInit() calls zeGetRTASBuilderExpProcAddrTable() and
it fails because `GET_FUNCTION_PTR( drv.handle, "zeGetRTASBuilderExpProcAddrTable") )` is always null.

Any idea?

**Comment by lisanna-dettwyler** [comment]
The latest GPU driver available for your hardware does not implement `zeGetRTASBuilderExpProcAddrTable`, which suggests you're using a new loader with an old driver. I think it would be alright to allow certain function pointer lookups to fail to maintain backwards compatibility with such drivers.
