### ISSUE TITLE
ubuntu 24 support

### ISSUE THREAD

**Issue by Xyz00777** [oneapi-src/level-zero#197]
hi, when can we expect support of ubuntu 24, because thats an lts release again and newer than 22

**Comment by lisanna-dettwyler** [comment]
Are you looking for Ubuntu 24.04 artifacts in the releases? I think we can have those by the next release, which should be later this week. Otherwise, you should be able to compile under Ubuntu 24.04 and 24.10.

**Comment by lisanna-dettwyler** [comment]
Ubuntu 24.04 artifacts are available as of the latest release: https://github.com/oneapi-src/level-zero/releases/tag/v1.17.44
