### ISSUE TITLE
ZE_LOADER_DEBUG_TRACE always printing for arbitrary SYCL execution

### ISSUE THREAD

**Issue by hdelan** [oneapi-src/level-zero#201]
```
$ sycl-ls
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 
ZE_LOADER_DEBUG_TRACE:0 Drivers Discovered
[cuda:gpu][cuda:0] NVIDIA CUDA BACKEND, NVIDIA GeForce GTX 1050 Ti 6.1 [CUDA 12.6]
$ clang++ --version
clang version 20.0.0git (git@github.com:hdelan/llvm.git 93ee5b92cdd7502787c444181a34db0b736083b3)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/hugh/llvm/build/bin
Build config: +assertions
```

Maybe related to this: https://github.com/oneapi-src/level-zero/commit/b819cf27f1cbb28845e2efe5b116b14b4ccbdd44

Ping @nrspruit

**Comment by nrspruit** [comment]
Hello @hdelan this is fixed in https://github.com/oneapi-src/level-zero/commit/abdafead742cbd9a9ca0862eb0a56ff1a5be61a7

**Comment by hdelan** [comment]
Great thanks

**Comment by frasercrmck** [comment]
I think this was prematurely closed.

Note the original pointed out that `ZE_LOADER_DEBUG_TRACE:0 Drivers Discovered` was being printed. Correct me if I'm wrong but it still looks like it's being unconditionally printed here: https://github.com/oneapi-src/level-zero/blob/master/source/loader/ze_loader.cpp#L391-L396
