### ISSUE TITLE
Tracing callbacks get driver handles

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero#23]
From what I understand of the source code of both the loader and the driver, tracer callbacks get driver handles rather than loader handles (for level zero Objects). This raises a couple of issues:
 - If my tracer code is linked with the loader (binding, application adding tracepoints), I cannot use API calls inside the tracer using the handles obtained through the tracer callbacks.
 - In reverse, if, in the tracer, I override some arguments handles with ones obtained through API calls, those will be loader handles and cause issues with the driver call.

Am I correct?
Does this also mean that I cannot mix ddi API code with loader API code as objects would be different (unless I force loader intercept and ddi becomes moot)?

**Comment by gatorfax** [comment]
I think you're correct.  This is an issue we need to address.

**Comment by eero-t** [comment]
> I think you're correct. This is an issue we need to address.

@gatorfax is there some progress on this?

**Comment by jandres742** [comment]
@eero-t  please see https://github.com/oneapi-src/level-zero/tree/master/source/layers/tracing. The recommended layer to use is the one from the loader from link above. Please check if that addresses already the concern.

**Comment by eero-t** [comment]
Thanks! @Kerilk needs to answer this though, as he was the one bumping to the issue.

(I was just interested whether this got addressed in the past 1.5 years, in case I would need it later on myself.  I do not have currently any tracing code myself.)

**Comment by eero-t** [comment]
@Kerilk Thanks for verifying!  Only issue creator, and (subset of?) project members can close (and re-open?) an issue (not e.g. me).  It's simplest if the issue creator closes it after verifying that the issue is fixed...
