### ISSUE TITLE
clarify PCI mawBandwidth is not per lane

### ISSUE THREAD

**Issue by bgoglin** [oneapi-src/level-zero#26]
Hello

Several properties structures in the sysman API have a "maxBandwidth" field near a "width" field that says how many lanes are in the link. The documentation should say whether the bandwidth is per lane or not.

Matters at least for zet_fabric_port_speed_t and zet_pci_speed_t.

From what I see PciImp::init(), it's the total bandwidth for PCI, not per lane. That's not obvious at all (but OK if documented). I didn't check for fabric port speed.

Thanks

**Comment by eero-t** [comment]
Links to latest docs:
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-pci-speed-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-fabric-port-speed-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-fabric-port-properties-t

First one says it's sum of all lanes. Fabric port property struct containing fabric port speed structs states also that they are sum of all lines => can be closed as fixed.

**Comment by bgoglin** [comment]
Yes, thanks.
