### ISSUE TITLE
zeKernelGetAttribute(ZE_KERNEL_ATTR_SOURCE_ATTRIBUTE) fails validation

### ISSUE THREAD

**Issue by maleadt** [oneapi-src/level-zero#28]
https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/include/core/ze_module.h#L493-L506
vs
https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/source/layers/validation/ze_core_layer.cpp#L2630-L2631

**Comment by bmyates** [comment]
This API has been removed from the 1.0 specification.   The new API to use is `zeKernelSetIndirectAccess` I believe we have all validation bugs fixed. Thanks!
