### ISSUE TITLE
ZeEventPool(ze_event_pool_desc_t(ZE_EVENT_POOL_FLAG_TIMESTAMP)) fails validation

### ISSUE THREAD

**Issue by maleadt** [oneapi-src/level-zero#29]
https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/include/core/ze_event.h#L36-L44
vs
https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/source/layers/validation/ze_core_layer.cpp#L1287-L1288

**Comment by bmyates** [comment]
Thanks for identifying this issue. It's been fixed in latest:

https://github.com/oneapi-src/level-zero/blob/b843465bb269bc8f98c84d176b258ef7e3dd3bd6/source/layers/validation/ze_valddi.cpp#L1490-L1491
