### ISSUE TITLE
is there a public interface for the C++ API wrapper ?

### ISSUE THREAD

**Issue by fwyzard** [oneapi-src/level-zero#3]
Under `source/wrapper/` there is what looks like a C++ wrapper on top of the Level Zero C API.

While it is built into a set of libraries (`libze_api_cpp.a` and `libzet_api_cpp.a`), there doesn't seem to be any public interface for it.

**Comment by bmyates** [comment]
The C++ wrappers aren't fully implemented yet. We have some pending changes. Our current plan is for the C++ headers to be installed to the same directory as the C headers. Would this fit your use model?

**Comment by fwyzard** [comment]
That would be perfect, thanks !

**Comment by bmyates** [comment]
Support for c++ wrappers has been added in 875fef26e2a4a2eb9f4f61dc25e35f30362dc5e9
