### ISSUE TITLE
zeEventCreate(ze_event_desc_t(ZE_EVENT_SCOPE_FLAG_HOST)) fails validation

### ISSUE THREAD

**Issue by maleadt** [oneapi-src/level-zero#30]
https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/include/core/ze_event.h#L127-L138
vs
https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/source/layers/validation/ze_core_layer.cpp#L1345-L1349

**Comment by maleadt** [comment]
Maybe I'm missing something obvious here, sorry for the noise in that case, but it looks like there's quite some instances where the validator stumbles on otherwise-valid enum values (which I verified function as expected without the validator).

**Comment by bmyates** [comment]
Thanks for the reports... you're not missing anything. This bug with flag checking exists at multiple locations in the validation layer.
We are currently working towards a version 1.0 candidate that will have these issues fixed.

**Comment by bmyates** [comment]
This issue has been fixed in the latest code. 

https://github.com/oneapi-src/level-zero/blob/b843465bb269bc8f98c84d176b258ef7e3dd3bd6/source/layers/validation/ze_valddi.cpp#L1551-L1555
