### ISSUE TITLE
Incorrect validation of zeEventPoolCreate

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero#35]
The validation enforces the number of event in the pool to be zero:
https://github.com/oneapi-src/level-zero/blob/b843465bb269bc8f98c84d176b258ef7e3dd3bd6/source/layers/validation/ze_valddi.cpp#L1493-L1494

Whereas the documentation of `struct ze_event_pool_desc_t` specifies:
>uint32_t count
>
>    [in] number of events within the pool; must be greater than 0

**Comment by bmyates** [comment]
Thanks for pointing this out. I'll fix this.
