### ISSUE TITLE
pkg-config file for level-zero missing

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero#37]
pkg-config is the standard interface of declaring project version, include paths and libraries: https://en.wikipedia.org/wiki/Pkg-config

It's used by most open source projects and all build systems support using it for checking these details. I think level-zero should also install level-zero.pc file with this info.

**Comment by bmyates** [comment]
Hi @eero-t please test out the pkg-config file added in https://github.com/oneapi-src/level-zero/commit/cacdcf19e0055f832a69671a6b59c25c0564b554

**Comment by eero-t** [comment]
Will do after the next tagged L0 version.
