### ISSUE TITLE
libze_loader.so loads itself.

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero#39]
Hello,

The library part of libze_loader.so loads itself:
https://github.com/oneapi-src/level-zero/blob/2fb87e7aec2cf94bfe191fc2ce64d12cca321add/source/lib/ze_lib.cpp#L32

This makes sense should the library be built as a standalone one and needs to open the loader library.
This is harmful for the loader itself as it can be made to use external symbols for it's initialization. The most simple example I can think of is:
```c
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

typedef int (*zeInit_t)();

int main() {
    const char *s;

    s = getenv("ZELIBPATH");       
    if (!s) {
        printf("No path given.\n");
        exit(1);
    }

    void *handle = NULL;
    handle = dlopen(s, RTLD_LAZY | RTLD_LOCAL);
    if (!handle) {
        printf("Wrong path given.\n");
        exit(1);
    }

    zeInit_t pf = (zeInit_t)(intptr_t)dlsym(handle, "zeInit");
    int res = (*pf)(0);
    if (res != 0)
        printf("Error.\n");
    else
        printf("Success.\n");
}
```
Compiling the sample and invoking it with (and with 2 different ze_loader installation):
```bash
LD_PRELOAD=/path/to/first/libze_loader.so ZELIBPATH=/path/to/second/libze_loader.so a.out 
```
will cause a segfault, because the second ze_loader will try to use the first ze_loader symbols to initialize itself.
I think the loader shouldn't be trying to open itself, and use a different mechanism if the library is standalone or used inside a loader.

I hope I made a good enough job of explaining the issue.

Thanks,
Brice

**Comment by bmyates** [comment]
Hi @Kerilk - Yep, I understand what you're saying. I agree the loader shouldn't be trying to open itself when it's compiled as a standalone library.  I'll see if I can fix this.

**Comment by bmyates** [comment]
This should be fixed by https://github.com/oneapi-src/level-zero/commit/7349a2306bb5174252b3e47bb939a1aaae107fdc

**Comment by Kerilk** [comment]
Thanks for the quick fix. Seems fine to me as long as the library is opened with `RTLD_DEEPBIND`. If the library were to be opened without it, the symbols could still be overridden.

**Comment by bmyates** [comment]
Closing old issues. 

The library is opened with `RTLD_DEEPBIND` and we haven't run into any problems with this approach.
