### ISSUE TITLE
Defines in headers don't match engine groups in linked OneAPI Sysman documentation

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero#40]
Documentation here: https://spec.oneapi.com/level-zero/latest/sysman/api.html#_CPPv418zes_engine_group_t

Lists following defines:
* ZES_ENGINE_GROUP_RENDER_ALL
* ZES_ENGINE_GROUP_3D_SINGLE
* ZES_ENGINE_GROUP_3D_ALL
* ZES_ENGINE_GROUP_3D_RENDER_COMPUTE_ALL
* ZES_ENGINE_GROUP_MEDIA_ENHANCEMENT_SINGLE

However, they're missing from the latest L0 header:  https://github.com/oneapi-src/level-zero/blob/master/include/zes_api.h#L1086

(And the values of several defines differ from the documentation.)

Ps. Link to L0 specification at end of README.md gives 404.  Spec link in the sidebar works.

**Comment by eero-t** [comment]
Ping... Is either the spec or header going to be fixed?

**Comment by bmyates** [comment]
This seems to be an error in posting to the spec. These enum values shouldn't be added until the 1.1 release of spec and headers.

**Comment by eero-t** [comment]
Latest release is v1.2.3, and that includes the new defines from the spec, so closing this.
