### ISSUE TITLE
loader::zeCommandQueueExecuteCommandLists "spoils" the input command list handles

### ISSUE THREAD

**Issue by skuka** [oneapi-src/level-zero#43]
loader::zeCommandQueueExecuteCommandLists "spoils" the input command list handles.
ze_ldrddi.cpp:818 - 819
I'm quite confused because now I do not understand how it has been working all this time...
Normally user has a local variable ze_command_list_handle_t cmd_list and passes it to zeCommandQueueExecuteCommandLists by address. 
It's quite unexpected that its value changes after the call. And I guess it becomes non-usable for the further API calls like Destroy, or Reset, etc?
Is it just that this implementation is not used in the default case? 
I got to this code from a machine with igfx + dgfx running 2 different drivers.

**Comment by bmyates** [comment]
Agreed, the loader should not be modifying phCommandLists.  I will work on a fix.

> Is it just that this implementation is not used in the default case?

Yep, exactly.  This function is only used if there is more than 1 driver or if `ZE_ENABLE_LOADER_INTERCEPT` env variable is set to true.  The function pointer tables for command queues are set up here https://github.com/oneapi-src/level-zero/blob/d4cf1071a701e6007acda35b4b60d59af79f3792/source/loader/ze_ldrddi.cpp#L4160

**Comment by bmyates** [comment]
This has been fixed in https://github.com/oneapi-src/level-zero/commit/282f4317fee902811df91e70bb52c19844e7bfc9
