### ISSUE TITLE
8th generation gpu support

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/level-zero#5]
Is it possible that level 0 can support Broadwell GPUs ?

I got segfault when running a program as shown below.

Thread 1 "a.out" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff6573b94 in L0::Kernel::create(unsigned int, L0::Module*, _ze_kernel_desc_t const*, _ze_result_t*) ()
   from /usr/local/lib/libze_intel_gpu.so.0.8
#2  0x00007ffff6575cf6 in L0::ModuleImp::createKernel(_ze_kernel_desc_t const*, _ze_kernel_handle_t**) ()
   from /usr/local/lib/libze_intel_gpu.so.0.8
#3  0x00007ffff6568207 in L0::BuiltinFunctionsLibImpl::loadBuiltIn(unsigned int, char const*) ()
   from /usr/local/lib/libze_intel_gpu.so.0.8
#4  0x00007ffff656832b in L0::BuiltinFunctionsLibImpl::initFunctions() () from /usr/local/lib/libze_intel_gpu.so.0.8
#5  0x00007ffff656bb9d in L0::Device::create(L0::DriverHandle*, NEO::Device*) () from /usr/local/lib/libze_intel_gpu.so.0.8
#6  0x00007ffff656cc0b in L0::DriverHandleImp::initialize(std::vector<std::unique_ptr<NEO::Device, std::default_delete<NEO::Device> >, std::allocator<std::unique_ptr<NEO::Device, std::default_delete<NEO::Device> > > >) () from /usr/local/lib/libze_intel_gpu.so.0.8
#7  0x00007ffff656cd9b in L0::DriverHandle::create(std::vector<std::unique_ptr<NEO::Device, std::default_delete<NEO::Device> >, std::allocator<std::unique_ptr<NEO::Device, std::default_delete<NEO::Device> > > >) () from /usr/local/lib/libze_intel_gpu.so.0.8
#8  0x00007ffff656da0a in L0::DriverImp::initialize(bool*) () from /usr/local/lib/libze_intel_gpu.so.0.8
#9  0x00007ffff656d60e in ?? () from /usr/local/lib/libze_intel_gpu.so.0.8
#10 0x00007ffff621c827 in __pthread_once_slow () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007ffff656d8f0 in L0::init(_ze_init_flag_t) () from /usr/local/lib/libze_intel_gpu.so.0.8
#12 0x00007ffff7b2df6a in zeInit () from /usr/local/lib/libze_loader.so.0.91
#13 0x0000555555557285 in main ()

**Comment by rwmcguir** [comment]
This repository is almost entirely vendor and hardware agnostic. I think what you are looking for is filing an issue with www.github.com/intel/compute-runtime .   The only vendor support here is just being aware of vendors to load their specific implementations.

So to answer your question: Level Zero as a specification and loader can support anything, however it is up to the vendor and specific hardware driver/support to implement specific things and hardware. I would suggest heading over to the other github link I mentioned above and filing issue there, or seeeing if an existing issue was discussed in the past.

**Comment by jinz2014** [comment]
Thanks.
