### ISSUE TITLE
Usage of _ze_module_desc_t

### ISSUE THREAD

**Issue by aarontcopal2** [oneapi-src/level-zero#6]
To create a Module, you need to pass a module description. [(link)](https://github.com/oneapi-src/level-zero/blob/f50b570045e320264b9d46eb83d01838a06feca8/include/core/ze_module.h#L55)
```
typedef struct _ze_module_desc_t
{
    ze_module_desc_version_t version;
    ze_module_format_t format;
    size_t inputSize;                               ///< [in] size of input IL or ISA from pInputModule.
    const uint8_t* pInputModule;                    ///< [in] pointer to IL or ISA
    const char* pBuildFlags;
    const ze_module_constants_t* pConstants;
} ze_module_desc_t;
```
I'm having trouble determining the 3rd and 4th argument. Could someone provide me code samples of ze_module_desc_t for both "ZE_MODULE_FORMAT_IL_SPIRV" and "ZE_MODULE_FORMAT_NATIVE" format.

**Comment by jandres742** [comment]
`pInputModule` should point to the either the SPIRV or BIN code of the kernel you want to offload to the GPU, and with `format` you indicate the format you are passing. The SPIRV or BIN code is generated, for instance, using clang, as described here https://github.com/KhronosGroup/SPIR/tree/spirv-1.1.

We are planning on releases samples that you can use to have as reference. Please keep an eye on https://github.com/oneapi-src/level-zero-tests, which will have very soon Level Zero content.

**Comment by aarontcopal2** [comment]
Thank you. Could you close the issue when the samples are pushed to the repo?

**Comment by jandres742** [comment]
Sure. Once they are available, I will paste here a link to a sample and we can close it.

**Comment by jandres742** [comment]
https://github.com/oneapi-src/level-zero-tests contains now samples you can use as reference. In your case, please take a look at test_module.cpp

**Comment by aarontcopal2** [comment]
@jandres742 , thanks for the link. You can close the issue :)
