### ISSUE TITLE
v1.3. - Can't build level zero loader on windows MSVC 

### ISSUE THREAD

**Issue by kraszkow** [oneapi-src/level-zero#61]
The same way of building works for v.1.2.3:

`C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps>git clone https://github.com/oneapi-src/level-zero.git 
Cloning into 'level-zero'...

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps>cd level-zero  

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero>git checkout v1.3.0 
Note: switching to 'v1.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at ae10adc Bump minor version to from v1.2 to v1.3

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero>git log --pretty -1 
commit ae10adce3668158072f89cf511581bd48300ad36
Author: Brandon Yates <brandon.yates@intel.com>
Date:   Thu May 27 10:38:10 2021 -0400

    Bump minor version to from v1.2 to v1.3
    
    Signed-off-by: Brandon Yates <brandon.yates@intel.com>

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero>mkdir build 

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero>cd build 

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero\build>cmake .. -DCMAKE_BUILD_TYPE=Release -DOpenCL_INCLUDE_DIR=c:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\OpenCL-Headers -DCMAKE_INSTALL_PREFIX=c:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\install\level-zero -G "NMake Makefiles" 
-- The C compiler identification is MSVC 19.28.29333.0
-- The CXX compiler identification is MSVC 19.28.29333.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.23.0.windows.1") 
-- Using patch version from commit count in git repository: 0
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OpenCL_INCLUDE_DIR

-- Build files have been written to: C:/tools/builds/fB-KRWEF/0/ispc/ispc-deps/level-zero/build

C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero\build>nmake install 

Microsoft (R) Program Maintenance Utility Version 14.28.29333.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target ze_loader
[  2%] Building RC object source/CMakeFiles/ze_loader.dir/ZeLoaderVersion.rc.res
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.

[  4%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/ze_libapi.cpp.obj
ze_libapi.cpp
[  7%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/ze_libddi.cpp.obj
ze_libddi.cpp
[  9%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/zet_libapi.cpp.obj
zet_libapi.cpp
[ 12%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/zet_libddi.cpp.obj
zet_libddi.cpp
[ 14%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/zes_libapi.cpp.obj
zes_libapi.cpp
[ 17%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/zes_libddi.cpp.obj
zes_libddi.cpp
[ 19%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/zel_tracing_libapi.cpp.obj
zel_tracing_libapi.cpp
[ 21%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/zel_tracing_libddi.cpp.obj
zel_tracing_libddi.cpp
[ 24%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/ze_lib.cpp.obj
ze_lib.cpp
[ 26%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/ze_tracing_register_cb_libapi.cpp.obj
ze_tracing_register_cb_libapi.cpp
[ 29%] Building CXX object source/CMakeFiles/ze_loader.dir/lib/windows/lib_init.cpp.obj
lib_init.cpp
[ 31%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/ze_loader.cpp.obj
ze_loader.cpp
[ 34%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/ze_loader_api.cpp.obj
ze_loader_api.cpp
[ 36%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/ze_ldrddi.cpp.obj
ze_ldrddi.cpp
[ 39%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/zet_ldrddi.cpp.obj
zet_ldrddi.cpp
[ 41%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/zes_ldrddi.cpp.obj
zes_ldrddi.cpp
[ 43%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/zel_tracing_ldrddi.cpp.obj
zel_tracing_ldrddi.cpp
[ 46%] Building CXX object source/CMakeFiles/ze_loader.dir/loader/windows/driver_discovery_win.cpp.obj
driver_discovery_win.cpp
C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero\source\loader\windows\driver_discovery_win.cpp(37): error C2065: 'GUID_DEVCLASS_COMPUTEACCELERATOR': undeclared identifier
C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero\source\loader\windows\driver_discovery_win.cpp(39): error C3536: 'computeDrivers': cannot be used before it is initialized
C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero\source\loader\windows\driver_discovery_win.cpp(39): error C2661: 'std::vector<loader::DriverLibraryPath,std::allocator<loader::DriverLibraryPath>>::insert': no overloaded function takes 1 arguments
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.`

**Comment by Jemale** [comment]
> C:\tools\builds\fB-KRWEF\0\ispc\ispc-deps\level-zero\source\loader\windows\driver_discovery_win.cpp(37): error C2065: 'GUID_DEVCLASS_COMPUTEACCELERATOR': undeclared identifier

`GUID_DEVCLASS_COMPUTEACCELERATOR` is defined in the latest Windows 10 SDK, 10.0.19041.0. Upgrade to this version and it should work. 

#56, #58 including to add to Windows instructions being added

**Comment by kraszkow** [comment]
Thanks! Installing this version of Windows SDK resolves this issue.
