### ISSUE TITLE
`ze_image_memory_properties_exp_t` has no corresponding enum value in `ze_structure_type_t`

### ISSUE THREAD

**Issue by Kerilk** [oneapi-src/level-zero#64]
As the title says:
structure `ze_image_memory_properties_exp_t` has no corresponding enumeration value in `ze_structure_type_t`, so its `stype` field cannot be set.

**Comment by bmyates** [comment]
You're right, thanks for pointing this out. I'll add it.

**Comment by bmyates** [comment]
This was added in a previous release. 

`ZE_STRUCTURE_TYPE_IMAGE_MEMORY_EXP_PROPERTIES`
