### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by kemp2001** [oneapi-src/level-zero#74]
N/A

**Comment by kemp2001** [comment]
My version:

$ dpkg -l |grep -i level-zero
ii  intel-level-zero-gpu                   1.2.021182.9361-main                  amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
ii  level-zero                             1.5.0.1-main                          amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
ii  level-zero-dev                         1.5.0.1-main                          amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.

**Comment by jandres742** [comment]
@kemp2001  this seems more of a question for the driver implementation in https://github.com/intel/compute-runtime

**Comment by kemp2001** [comment]
> @kemp2001 this seems more of a question for the driver implementation in https://github.com/intel/compute-runtime

Closed.
