### ISSUE TITLE
Memory allocations limited to 4GB?

### ISSUE THREAD

**Issue by fwinter** [oneapi-src/level-zero#78]
Sorry, if this seems a dumb question. I'm super new to Level Zero and trying to build upon one of your examples..

When it comes to memory allocation (host/device/shared) I came across the statement that the maximum size for allocation is returned in `ze_device_properties_t.maxMemAllocSize`. Well, this returns on my system just a little under `2^32` or 4GB. The OS is 64 bit Ubuntu and has 64 GB RAM installed. Is this allocation limitation intentional?

I am looking ahead to systems which have dedicated GPUs with huge RAM installed and in our production application we typically allocate memory areas larger than 4GB. Am I seeing this allocation limitation because I'm using an Intel integrated HD graphics at the moment, or did I build Level Zero or the compute runtime in 32 bit somehow?

**Comment by jandres742** [comment]
hi @fwinter  please see here https://github.com/intel/compute-runtime/issues/481#issuecomment-986306573

**Comment by fwinter** [comment]
Thanks for the pointer! With ever-increasing GDDR sizes it seems only a matter of time when dropping the stateful route is required to keep a competitive edge in the field. Scientific computing workloads require big allocations that NV and AMD already allow.
