### ISSUE TITLE
Any CHANGELOG for different SPEC versions?

### ISSUE THREAD

**Issue by jjfumero** [oneapi-src/level-zero#79]
Hi all, 
  is there any documentation of CHANGELOG that explains the differences between different versions in the oneAPI LevelZero SPEC? 
I see the latest now is 1.3.7.: https://spec.oneapi.io/level-zero/latest/index.html#l0-full-name-l0-spec-version 

Thank you

**Comment by jjfumero** [comment]
Thank you @bmyates , I think it would be great to include a changelog file.

**Comment by oscarbg** [comment]
+1

**Comment by eero-t** [comment]
Any news on getting changelogs?

**Comment by jjfumero** [comment]
@eero-t  Is this what you are looking for? https://spec.oneapi.io/releases/index.html#level-zero

**Comment by eero-t** [comment]
@jjfumero Yes, that looks good to me.  If it's OK for you too, you could close this bug!
