### ISSUE TITLE
Query position index in event pool out of an event handle

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/level-zero#90]
L0 event involves a position index inside event pool. However given an event handle, there is no way to tell what the index was, which complicates the situation when people freed the event and want to reuse the slot. It would be nicer to have an interface querying the index, or a ```zeEventDestroyAndReturnIndex``` something like that.

**Comment by jandres742** [comment]
hi @CaoZhongZ 
thanks for your question. 

would you mind posting your question directly on the spec repo? we have it now and we are working on moving all issues there. Thanks

https://github.com/oneapi-src/level-zero-spec/issues
