### ISSUE TITLE
Spec does not specify timestamp unit for all metric types

### ISSUE THREAD

**Issue by eero-t** [oneapi-src/level-zero#99]
Timestamp unit / resolution is explicitly specified as microseconds for following metrics:
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-pci-stats-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-engine-stats-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-fabric-port-throughput-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-freq-throttle-time-t
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-power-energy-counter-t

But not for:
* https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-mem-bandwidth-t

Same microsecond resolution is implied by the provided algorithm, but it should be explicitly stated also for memory bandwidth.

PS. Maybe there could be also some generic statement at start of all timestamps in the Sysman API being reported as microseconds, regardless of what resolution HW actually offers for the backend.  Or is it possible that the nanoseconds and cycles mentioned in core API (https://spec.oneapi.io/level-zero/latest/core/api.html#ze-device-properties-t) could be used in Sysman API later on?

**Comment by bmyates** [comment]
Hi, there's a recently created repo for the L0 spec.  This question would fit better there. 
 https://github.com/oneapi-src/level-zero-spec

**Comment by eero-t** [comment]
Ok, I'll close this issue after README here gets a link to that project: https://github.com/oneapi-src/level-zero/blob/master/README.md

**Comment by eero-t** [comment]
Thanks!
